# Generated by Django 4.0.2 on 2022-04-20 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waitlist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='waitlistenty',
            old_name='firts_name',
            new_name='first_name',
        ),
    ]
